#if !canImport(ObjectiveC)
  import XCTest

  extension Base32CrockfordTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base32CrockfordTests = [
      ("testExample", testExample),
      ("testGenerateArray", testGenerateArray),
      ("testGenerateArrayLessThanZero", testGenerateArrayLessThanZero),
      ("testIdentifierDataTypeCodable", testIdentifierDataTypeCodable),
      ("testMinimumUniqueCount", testMinimumUniqueCount),
      ("testMinimumUniqueCountLessThanZero", testMinimumUniqueCountLessThanZero),
      ("testUUID", testUUID)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(Base32CrockfordTests.__allTests__Base32CrockfordTests)
    ]
  }
#endif
